# Generated by Django 4.1.5 on 2023-01-30 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/d%/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поста'),
        ),
    ]
